### ISSUE TITLE
Avoid scrollable areas in scroll areas

### ISSUE THREAD

**Issue by solomon23** [Chris-Perkins/Lifting-Buddy#1]
When doing a session and adding a set. Try to avoid the scrollable area set table and just make the outer box larger.  This way you’ll avoid the dreaded scroll area within a scroll area

**Comment by Chris-Perkins** [comment]
Thanks for the feedback! Good to know someone's using the app :)
Are you suggesting the tableview should handle like the "add progression tracker" table in that the table's scrolling function is disabled and simply grows to be the size of all cells?

**Comment by solomon23** [comment]
Yea. Or not use a table view and add a “row” and wire it via auto layout. I haven’t looked at the code but I’m guessing autolayout is being used and should grow the parent

**Comment by Chris-Perkins** [comment]
Alright I believe I understand what you mean. I'm going to group this under the "Workout Start Rework" activity from the readme. This should be done in either 1.3 or 1.4. :)

**Comment by Chris-Perkins** [comment]
Hey Solomon! Checking in to let you know I have removed the scrollview within the workout session scrollview. I have a working example here: https://drive.google.com/open?id=1Z-NaLMD8v0lKvTwKyCPrl9I6G5hvmxuJ

Let me know what you think. This should be out in the 1.4 release as planned! 👍

**Comment by Chris-Perkins** [comment]
Hey there solomon! I believe the rework has completely fixed this issue, and so I will be closing it. That said, if you have any feedback after the update hits your phone, feel free to reach out and open another issue with your thoughts.

Thanks for using Lifting Buddy! :)
